# Predicting the drug to be prescribed based on the information provided by the patient

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [6]:
df=pd.read_csv("D:\\Datascience\\Data Sets\\drug200.csv")
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["Sex"]=le.fit_transform(df["Sex"])
df["BP"]=le.fit_transform(df["BP"])
df["Cholesterol"]=le.fit_transform(df["Cholesterol"])
df["Drug"]=le.fit_transform(df["Drug"])

In [9]:
df.head()

Age  Sex  BP  Cholesterol  Na_to_K  Drug
0   23    0   0            0   25.355     0
1   47    1   1            0   13.093     3
2   47    1   1            0   10.114     3
3   28    0   2            0    7.798     4
4   61    0   1            0   18.043     0

In [10]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [11]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
from sklearn.svm import SVC
svm=SVC()
svm.fit(xtrain,ytrain)
ypred=svm.predict(xtest)

In [14]:
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix
print(f"Accuracy:-{accuracy_score(ytest,ypred)}")
print(f"Classification Report:-{classification_report(ytest,ypred)}")
print(f"Confusion matrix:-{confusion_matrix(ytest,ypred)}")

Accuracy:-0.825
Classification Report:-              precision    recall  f1-score   support

           0       0.95      1.00      0.97        19
           1       0.00      0.00      0.00         3
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         3
           4       0.70      1.00      0.82        14

    accuracy                           0.82        40
   macro avg       0.33      0.40      0.36        40
weighted avg       0.70      0.82      0.75        40

Confusion matrix:-[[19  0  0  0  0]
 [ 0  0  0  0  3]
 [ 0  0  0  0  1]
 [ 1  0  0  0  2]
 [ 0  0  0  0 14]]
